### PR TITLE
Added more networking information

### PR DESCRIPTION
**Pull request by tuxudo**
New client tab, more networking related information, new client script and migration

### CODE REVIEW

**Comment by bochoven** [comment]
Any chance you could fix the conflicts?

**Comment by tuxudo** [comment]
I think I updated the listing correctly

**Comment by bochoven** [comment]
It does not install here

**Comment by tuxudo** [comment]
I'm not sure what you mean by it not installing

**Comment by bochoven** [comment]
Oh, I had copied the module to network.orig, which was uninstalling the script...

**Comment by bochoven** [comment]
You need to get the code more DRY though: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Pull request merged**
